apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-frontend
  labels:
    app: astro-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: astro-frontend
  template:
    metadata:
      labels:
        app: astro-frontend
    spec:
      containers:
      - name: astro
        image: astro:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m" 