name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-payload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Payload Docker image
      working-directory: ./payload
      run: |
        docker build . --file Dockerfile --tag payload:$(date +%s)
        
  build-astro:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Astro Docker image
      working-directory: ./astro-project
      run: |
        docker build . --file Dockerfile --tag astro:$(date +%s)
